FROM node:22-alpine

WORKDIR /app

# Копируем зависимости
COPY app/package*.json /app/

# Устанавливаем зависимости
RUN npm install

# Копируем исходный код
COPY app/ /app/

# Открываем порт для Vite
EXPOSE 5173

# Добавляем переменные окружения для Vite
ENV HOST=0.0.0.0
ENV PORT=5173
