version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - celery
    env_file:
      - .env
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
    networks:
      - note_network
    restart: always

  mongo:
    image: mongo:8.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - note_network

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - note_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    depends_on:
      - redis
      - mongo
    command: celery -A worker.celery worker --loglevel=info
    env_file:
      - .env
    environment:
      - CELERY_HOST=redis
      - CELERY_PORT=6379
    networks:
      - note_network
    restart: always


volumes:
  mongo_data:
    driver: local


networks:
  note_network:
    driver: bridge
