name: BackendCheck

on:
    push:
        paths:
          - 'backend/**' 
    pull_request:
        paths:
          - 'backend/**' 


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        working-directory: backend
        run: poetry install

      - name: Lint with flake8
        working-directory: backend
        run: |
          poetry run pip install flake8
          poetry run flake8 .

      - name: Run tests
        working-directory: backend
        run: poetry run pytest

    